name: Go CD Project Process
on:
  push:
    branches: [main]
jobs:
  build-and-send-to-telegram:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Create Keystore
        run: keytool -genkeypair -v -storetype PKCS12 -keystore booksapp.keystore -alias booksapp -keyalg RSA -keysize 2048 -validity 10000

      - name: Move Keystore to Android
        run: mv ./booksapp.keystore ./android/app/booksapp.keystore

      - name: Execute Gradle
        run: cd android && chmod +x ./gradlew

      - name: Build Android Release
        run: cd android && ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: release
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Upload to Telegram Bot
        run: |
          cd android/app/build/outputs/apk/release/
          curl -X POST -H 'Content-Type: multipart/form-data' -F "chat_id=${{secrets.TG_CHAT_ID}}" -F text='App is Released!' ${{secrets.TG_BOT_TOKEN}}/sendMessage
          curl -X POST -H 'Content-Type: multipart/form-data' -F "chat_id=${{secrets.TG_CHAT_ID}}" -F document=@app-release.apk ${{secrets.TG_BOT_TOKEN}}/sendDocument
