name: Build Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
   
      - name: Install Dependencies
        run: npm install
      
      - name: Make Gradle Executable
        run: cd android && chmod +x ./gradlew
      
      - name: Cleaning
        run: |
          cd android
          ./gradlew clean
          ./gradlew cleanBuildCache
          cd ..
          
      - name: Build
        run: |
          cd android
          ./gradlew assembleRelease
          cd ..
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: release
          path: android/app/build/outputs/apk/release/app-release.apk
          
      - name: Upload to Telegram Bot
        run: |
          cd android/app/build/outputs/apk/release
          curl -X POST -H 'Content-Type: multipart/form-data' -F "chat_id=${{secrets.TG_CHAT_ID}}" -F text='App Release!' ${{secrets.TG_BOT_TOKEN}}/sendMessage
          curl -X POST -H 'Content-Type: multipart/form-data' -F "chat_id=${{secrets.TG_CHAT_ID}}" -F document=app-release.apk ${{secrets.TG_BOT_TOKEN}}/sendDocument

          
        
